services:
  mysql:
    container_name: 'notification-scheduled-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=notificationscheduled'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'